spring:
  application:
    name: USER-SERVICE
    
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommUser
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
